<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { getPublicNewsPage } from '@/http/news'
const router = useRouter(); const loading = ref(false); const news = ref<any[]>([]); const keyword = ref('')
const load = async () => { loading.value = true; try { const r:any = await getPublicNewsPage({ currentPage: 1, pageSize: 30, params: keyword.value ? [{name:'keyword',value:keyword.value}] : [] }); news.value = r.data?.records || [] } finally { loading.value = false } }
onMounted(load)
</script>
<template>
  <div class="portal"><header class="top"><div class="top-inner"><div class="identity"><div class="seal"> <span> </span></div><div><strong>数学与计算科学学院</strong><small>School of Mathematics & Computing Science</small></div></div><div class="tools">加入收藏　|　学校主页 <el-input v-model="keyword" size="small" placeholder="请输入关键字搜索" @keyup.enter="load" /></div></div></header>
  <nav><div class="nav-inner"><a class="active">首页</a><a>学院概况</a><a>师资队伍</a><a>本科生教育</a><a>研究生教育</a><a>科学研究</a><a>党建工作</a><a>学生工作</a><a>人才招聘</a><router-link to="/login" class="admin">管理入口</router-link></div></nav>
  <main><div class="hero"><div><span>MATHEMATICS</span><b>凝聚奋进力量　擘画高质量发展新蓝图</b></div></div><div class="section-title"><span>学院新闻</span><em>NEWS</em></div><div v-loading="loading" class="news-grid"><article v-for="item in news" :key="item.id" @click="router.push(`/site/news/${item.id}`)"><h3>{{item.title}}</h3><time>{{(item.publishTime || item.createTime || '').slice(0,10)}}</time><p>{{item.supplier ? `供稿：${item.supplier}` : '学院新闻'}}</p></article><el-empty v-if="!loading&&!news.length" description="暂无已发布新闻" /></div></main><footer>Copyright© 2026 桂林电子科技大学数学与计算科学学院</footer></div>
</template>
<style scoped>
*{box-sizing:border-box}.portal{min-height:100vh;background:#fff;color:#24354b}.top{height:118px;background:#fff}.top-inner{max-width:1080px;height:100%;margin:auto;display:flex;justify-content:space-between;align-items:center}.identity{display:flex;gap:14px;align-items:center;color:#1e4d86}.identity strong{display:block;font-size:25px;font-weight:600}.identity small{display:block;font-size:11px;letter-spacing:.5px}.seal{font-size:27px;font-weight:700;border:3px solid #1e4d86;border-radius:50%;width:62px;height:62px;display:grid;place-items:center;transform:rotate(-8deg)}.seal span{font-size:18px}.tools{font-size:11px;color:#8c98a6;text-align:right;align-self:flex-start;padding-top:14px}.tools .el-input{display:block;width:190px;margin-top:13px}.portal nav{background:#19558f;height:40px}.nav-inner{max-width:1080px;margin:auto;display:flex;align-items:center;height:100%;gap:28px}.nav-inner a{color:#fff;text-decoration:none;font-size:13px;cursor:pointer}.nav-inner a.active,.nav-inner a:hover{color:#f4d77a}.admin{margin-left:auto!important;font-size:12px!important}main{max-width:1080px;margin:auto;padding:18px 0 45px}.hero{height:190px;background:linear-gradient(110deg,#9d3b32,#e78553 50%,#ad4434);position:relative;display:flex;align-items:center;justify-content:center;color:#fff;text-align:center}.hero:after{content:'';position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent,transparent 3px,rgba(255,255,255,.05) 4px);pointer-events:none}.hero span{display:block;letter-spacing:5px;font-size:14px;opacity:.8}.hero b{font-size:32px;display:block;margin-top:12px;text-shadow:2px 2px 0 #8d3c25}.section-title{margin-top:20px;background:#225c96;color:#fff;height:38px;padding:0 15px;display:flex;align-items:center}.section-title span{font-size:15px}.section-title em{font-size:10px;margin-left:auto;opacity:.8}.news-grid{min-height:240px;display:grid;grid-template-columns:repeat(3,1fr);gap:0 24px;border:1px solid #e5e8eb;border-top:0;padding:4px 14px}.news-grid article{position:relative;padding:12px 50px 12px 10px;border-bottom:1px dotted #c5ccd4;cursor:pointer}.news-grid article:hover h3{color:#1b65a3}.news-grid h3{font-size:13px;font-weight:400;margin:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.news-grid time{position:absolute;right:8px;top:12px;font-size:11px;color:#929ba6}.news-grid p{font-size:11px;color:#9aa3ae;margin:7px 0 0}footer{height:68px;background:#244f7e;color:#fff;text-align:center;padding-top:27px;font-size:11px}@media(max-width:800px){.top{height:auto;padding:18px}.top-inner{display:block}.tools{text-align:left;margin-top:12px}.nav-inner{overflow:auto;padding:0 15px;gap:18px;white-space:nowrap}.admin{display:none!important}main{padding:12px}.hero{height:145px}.hero b{font-size:22px}.news-grid{grid-template-columns:1fr}.identity strong{font-size:20px}}
</style>
